FROM ubuntu:18.04

# https://developer.tizen.org/development/tizen-studio/download
ARG TIZEN_SDK_VER="3.7"
ARG TIZEN_SDK_URL="http://download.tizen.org/sdk/Installer/tizen-studio_${TIZEN_SDK_VER}/web-cli_Tizen_Studio_${TIZEN_SDK_VER}_ubuntu-64.bin"
ARG TIZEN_HOME="/home/tizen"

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y && \
    apt install --no-install-recommends -y  \
    default-jdk \
    pciutils \
    zip \ 
    libcurl3-gnutls \
    expect \
    gettext  \
    python2.7 \
    libwebkitgtk-1.0-0 \
    rpm2cpio \
    make \
    cpio \
    ruby \
    libxcb-icccm4 \
    libxcb-render-util0 \
    libxcb-image0 \
    acl \
    libsdl1.2debian \
    libxcb-randr0 \
    bridge-utils \
    openvpn \
    libcanberra-gtk-module \
    libv4l-0 \
    libvirt-bin \
    libxcb-shape0 \
    libxtst6 \
    qemu-kvm \
    sudo \
    zenity \
    wget \
    tree \
    libssl1.0.0 \
    libssl-dev \
    libpng-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${TIZEN_HOME}/bin && \
    wget -q -O ${TIZEN_HOME}/tizen_sdk.bin ${TIZEN_SDK_URL} && \
    chmod +x ${TIZEN_HOME}/tizen_sdk.bin

RUN adduser --no-create-home --disabled-password --gecos ''  tizen && \
    chown -R tizen: /home/tizen && \
    chmod -R 777 /home/tizen && \
    usermod --home /home/tizen tizen && \
    touch /home/tizen/.bashrc && \
    echo "PATH=$PATH:/home/tizen/bin" >> /home/tizen/.bashrc

USER tizen
WORKDIR /home/tizen
RUN ls -la . 
RUN yes | ./tizen_sdk.bin

WORKDIR /home/tizen/tizen-studio/package-manager
RUN ./package-manager-cli.bin install --accept-license Baseline-SDK  && \
    ./package-manager-cli.bin install --accept-license TOOLS  && \
    ./package-manager-cli.bin install --accept-license NativeToolchain && \
	./package-manager-cli.bin install --accept-license EXTRAS && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Public && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Public-Emulator && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Public-WebAppDevelopment && \
	./package-manager-cli.bin install --accept-license cert-add-on  && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Extension-Tools && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Extension-Resources


ENV PATH="/home/tizen/tizen-studio/tools/ide/bin/:${PATH}"
ENV PATH="/home/tizen/tizen-studio/tools/:${PATH}"

