FROM ubuntu:18.04

# https://developer.tizen.org/development/tizen-studio/download
ARG TIZEN_SDK_VER="3.7"
ARG TIZEN_SDK_URL="http://download.tizen.org/sdk/Installer/tizen-studio_${TIZEN_SDK_VER}/web-cli_Tizen_Studio_${TIZEN_SDK_VER}_ubuntu-64.bin"
ARG TIZEN_HOME="/home/tizen"

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y && \
    apt install -y  \
    default-jdk \
    pciutils \
    zip \ 
    libcurl3-gnutls \
    libglib2.0-0 \
    expect \
    gettext \
    python2.7 \
    libwebkitgtk-1.0-0 \
    rpm2cpio \
    make \
    cpio \
    ruby \
    libxcb-icccm4 \
    libxcb-render-util0 \
    libxcb-image0 \
    acl \
    libsdl1.2debian \
    libxcb-randr0 \
    bridge-utils \
    openvpn \
    libcanberra-gtk-module \
    libv4l-0 \
    libvirt-bin \
    libxcb-shape0 \
    libxtst6 \
    qemu-kvm \
    sudo \
    zenity \
    wget \
    tree \
    libssl1.0.0 \
    libssl-dev && \
    wget http://se.archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb && \
    dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb && rm libpng12-0_1.2.54-1ubuntu1_amd64.deb && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --gecos ''  tizen && \
    mkdir -p ${TIZEN_HOME}/bin && \
    wget -q -O ${TIZEN_HOME}/tizen_sdk.bin ${TIZEN_SDK_URL} && \
    chmod +x ${TIZEN_HOME}/tizen_sdk.bin

USER tizen
ENV PATH="${TIZEN_HOME}/bin:${PATH}"
WORKDIR "${TIZEN_HOME}"
RUN ls -la . && \
    yes | ./tizen_sdk.bin

WORKDIR "${TIZEN_HOME}/tizen-studio/package-manager"
RUN ./package-manager-cli.bin install --accept-license Baseline-SDK
RUN ./package-manager-cli.bin install --accept-license NativeToolchain
RUN ./package-manager-cli.bin install --accept-license TOOLS
RUN ./package-manager-cli.bin install --accept-license EXTRAS
RUN ./package-manager-cli.bin install --accept-license TV-SAMSUNG-Public && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Public-Emulator && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Public-WebAppDevelopment && \
	./package-manager-cli.bin install --accept-license cert-add-on  && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Extension-Tools && \
	./package-manager-cli.bin install --accept-license TV-SAMSUNG-Extension-Resources

ENV PATH="${TIZEN_HOME}/tizen-studio/tools/ide/bin:${PATH}"
ENV PATH="${TIZEN_HOME}/tizen-studio/tools:${PATH}"

CMD [ "/bin/bash" ]
